spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys-basis-mybatis?userUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    schema: classpath:db/schema-mysql.sql
    data: classpath:db/data-mysql.sql
    initialization-mode: never

  redis:
    password: luoren
# Logger Config
logging:
  level:
    top.luoren.basis: debug


# JWT
jwt:
  header: Authorization
  secret: mySecret
  #token有效期一天
  expiration: 86400

